---

- name: collect hosts configuration
  include: collect-hosts.yaml

- name: Ensure zuul group exists
  group:
    name: zuul
    state: present
    gid: 9999

- name: Ensure zuul user exists
  user:
    name: "zuul"
    state: present
    uid: 9999
    groups: docker,zuul
    append: yes

- name: create required directories
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    follow: no
    mode: 0755
    owner: zuul
    group: zuul
  with_items:
    - /var/log/zuul
    - /var/lib/zuul
    - /var/lib/zuul/builds
    - /var/lib/zuul/git
    - /var/lib/zuul/ssh
    - /var/lib/zuul/keys

- name: protect zuul keys folders
  file:
    path: "{{ item }}"
    mode: 0700
    owner: zuul
    group: zuul
  with_items:
    - /var/lib/zuul/keys
