---

- name: check cloud definition
  stat:
    path: /etc/cloud/cloud.yaml
  register: stat_result_cloud

- fail:
    msg: "Please create /etc/cloud/cloud.yaml"
  when: stat_result_cloud.stat.exists == False

- name: build containers
  include_role:
    name: build
    tasks_from: nodepool
  vars:
    - component: builder
  when: nodepool_build_containers

- name: detect if built container exists (check for latest tag)
  when: not nodepool_build_containers
  block:
    - command: "docker image inspect {{ NODEPOOL_DOCKERREPO }}/nodepool-builder:latest"
      register: di_check_res
      no_log: true
    - set_fact:
        NODEPOOL_VERSION: latest
      when: di_check_res is success

- name: create required directories
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    mode: 0750
  with_items:
    - /opt/nodepool-builder/etc_nodepool
    - /opt/nodepool-builder/.ssh
    - /opt/nodepool/images
    - /var/log/zuul

- name: copy ssh keys
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    force: true
    mode: 0600
  with_items:
    - {src: "{{ gerrit_ssh_keys }}/zuul_rsa", dest: "/opt/nodepool-builder/ssh_keys/"}
    - {src: "{{ gerrit_ssh_keys }}/nodepool_rsa.pub", dest: "/opt/nodepool-builder/ssh_keys/"}

- name: remove config directory
  file:
    path: /opt/nodepool-builder/config
    state: absent

- name: "clone {{ zuul_config_project }}"
  git:
    repo: "zuul_config_project_git_url"
    dest: /opt/nodepool-builder/config
    accept_hostkey: yes
    force: true
    key_file: /opt/nodepool-builder/ssh_keys/zuul_rsa

- name: copy config files
  copy:
    src: "./"
    dest: "/opt/nodepool-builder"
    force: true
    mode: 0600

- name: apply docker-compose configuration
  template:
    src: docker-compose.yaml.j2
    dest: /opt/nodepool-builder/docker-compose.yaml
    mode: 0600

- name: start nodepool-builder service
  docker_service:
    project_src: /opt/nodepool-builder/
    restarted: true
